### ISSUE TITLE
check_version may require minimum python version as 3.7 due to capture_output arg

### ISSUE THREAD

**Issue by manisnesan** [muellerzr/dependency_checker#6]
Python Version: 3.6.12

Reference: https://stackoverflow.com/questions/53209127/subprocess-unexpected-keyword-argument-capture-output/53209196

```
✗ python                        
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dependency_checker import get_installed_dependencies, check_new_version
>>> get_installed_dependencies('dependency-checker', depth_limit=1)
{'dependency-checker': '0.0.1', 'packaging': '20.8', 'pip': '20.3.3', 'pipdeptree': '2.1.0'}
>>> check_new_version('pipdeptree')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: check_new_version() missing 1 required positional argument: 'current_version'
>>> check_new_version('pipdeptree', '2.1.0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/msivanes/miniconda3/envs/fastchai/lib/python3.6/site-packages/dependency_checker/checker.py", line 39, in check_new_version
    latest_version = str(subprocess.run([sys.executable, '-m', 'pip', 'install', '{}==random'.format(package_name)], capture_output=True, text=True))
  File "/home/msivanes/miniconda3/envs/fastchai/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
>>> 
```

**Comment by manisnesan** [comment]
@muellerzr - Potential fix for this might be to change the minimum python version required to **3.7**

Validated locally.

```
✗ python                        
Python 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dependency_checker import get_installed_dependencies, check_new_version
>>> check_new_version('pipdeptree', '2.1.0')
False
```

**Comment by muellerzr** [comment]
Colab rocks python 3.7.x now, so I'd be okay with that change. Nice catch @manisnesan
